language: python
sudo: required
fast_finish: true

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
      env: CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal
    - os: linux
      dist: trusty
      python: 3.5
      env: CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal
    - os: osx
      language: generic
      python: 2.7
      env: PATH=/Library/Frameworks/GDAL.framework/Versions/2.1/unix/bin:$PATH

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo rm -vf /etc/apt/sources.list.d/*riak*; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:ubuntugis/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdal-bin libfftw3-dev libgdal-dev libgeotiff-dev geographiclib-tools libgeographiclib-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink gdal && (brew install gcc || brew link --overwrite gcc) && brew install geographiclib fftw; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install numpy; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install .; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-2.1.dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then X=$(echo `hdiutil mount GDAL_Complete-2.1.dmg | tail -1 | awk '{$1=$2=""; print $0}'` | xargs -0 echo) && sudo installer -pkg "${X}/"GDAL\ Complete.pkg -target /; export PATH="/Library/Frameworks/GDAL.framework/Programs:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install numpy; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install .; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -u tests/test_s2p.py --all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python2 -u tests/test_s2p.py --all; fi
